In [26]:
                                           # Practical 3.1
    
# for generate the random variable of Normal distribution
# Here are some technique to generate the random variable

import numpy as np

# loc is the mean (default = 0), scale is the standard deviation (default = 1)
random_numbers = np.random.normal(loc=0, scale=1, size=5)

# Step 2: Output the random numbers
random_numbers


array([ 0.40001555,  0.94685964, -1.39278314, -0.54219764,  0.07976961])

In [27]:
import random as np

# Generate a random floating point number between 0 and 1

# for int only => np.randint(a,b)

# for float only => np.uniform(a,b)

# for Probability Distribution => np.random.choice(value,size=5,p=probability) where value and probability are given

for i in range(5):
    print(np.random())  # Uniform distribution

0.8117309942714108
0.7879686299082969
0.5374063613705801
0.7524124421452889
0.5327007341619864


In [32]:
                                       # Practical 3.2
    
# Write a NumPy program to generate six random integers between 10 and 30
# # for int only => np.randint(a,b)
import random as np
for i in range(6):
    print(np.randint(10,30))

21
24
17
25
22
16


In [53]:
                                           # Practical 3.3
    
# Write a NumPy program to create a 3x3x3 array with random values.
import numpy as np

# There are four way to generate array matrix:

#  np.random.randn(d0, d1, ..., dn) where d0,d1,d2...row & column, of normal distribution witn mean(0),S.D.(1)

# np.random.randint(low, high, size) where within range and eg. size=3*3*3

# np.random.random(size) for range[0.0,1.0] of any size


#  np.random.rand(d0, d1, ..., dn) where d0,d1,d2...row & column filled with [0,1)

# for creation of  3*3*3 array
for i in range(27):
      random_arr=np.random.rand(3,3,3)
print(" The array is given as : \n",random_arr)


 The array is given as : 
 [[[0.48015923 0.30194844 0.81502449]
  [0.14558427 0.0882735  0.51754801]
  [0.31392142 0.72316919 0.08826195]]

 [[0.80361527 0.44213135 0.48957613]
  [0.53464482 0.41251088 0.35233802]
  [0.00187118 0.59416249 0.38994707]]

 [[0.61891155 0.65812558 0.91016328]
  [0.90895655 0.14640325 0.33498686]
  [0.98896588 0.35651229 0.01359986]]]


In [97]:
                                       # Practical 3.4

    #. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.
import numpy as np
ran_arr=np.random.randint(10,20,(5,5)) # for generate the random number within the range
print("Generated Array :\n",ran_arr)

# for max
max_num= np.max(ran_arr)
print(max_num)

# for min
min_num = np.min(ran_arr)
print(min_num)



Generated Array :
 [[17 17 18 12 11]
 [11 18 18 10 13]
 [11 11 17 13 17]
 [19 16 16 15 18]
 [16 14 16 15 14]]
19
10


In [104]:
                                      # Practical 3.5
    
# Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.
import numpy as np

# for generating the random number of 10*4
ran_arr=np.random.rand(10,4)  # It is use random generate within [0,1)
print("The random array is :\n",ran_arr)

# To extract the first five row so use indexing method
print("The five extract row is :\n",ran_arr[:5])


The random array is :
 [[0.72348203 0.99386444 0.50846948 0.64902862]
 [0.09592787 0.49359177 0.83491593 0.52249491]
 [0.53929572 0.38103359 0.95685712 0.61007635]
 [0.66515782 0.75743157 0.18802327 0.50717763]
 [0.20712143 0.73667884 0.32639523 0.82478973]
 [0.44895343 0.10150372 0.98055152 0.9980971 ]
 [0.64016881 0.38352273 0.59661155 0.81946244]
 [0.29466671 0.10246841 0.07723172 0.36026458]
 [0.45405702 0.27970182 0.94213738 0.80034947]
 [0.91691109 0.38276795 0.11013492 0.32394633]]
The five extract row is :
 [[0.72348203 0.99386444 0.50846948 0.64902862]
 [0.09592787 0.49359177 0.83491593 0.52249491]
 [0.53929572 0.38103359 0.95685712 0.61007635]
 [0.66515782 0.75743157 0.18802327 0.50717763]
 [0.20712143 0.73667884 0.32639523 0.82478973]]


In [3]:
                    # Practical 3.6
#  Write a NumPy program to check two random arrays are equal or not.
     
import numpy as np

# Generate two random arrays
arr1 = np.random.rand(3)  # Random array of size 5
arr2 = np.random.rand(3)  # Another random array of size 5

# Check if the arrays are equal
are_equal = np.array_equal(arr1, arr2)

print("Array 1:", arr1)

print("Array 2:", arr2)

print("Are the two arrays equal?", are_equal)
    

Array 1: [0.37130153 0.85008223 0.02398708]
Array 2: [0.27996434 0.50145214 0.39628731]
Are the two arrays equal? False


In [6]:
                       # Practical 3.7
# Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.

import numpy as np

# Generate a random vector of size 15
ran_vector = np.random.rand(15)
print(" The random vector is :\n",ran_vector)

# Replace the maximum value with -1
max_index = np.argmax(ran_vector)  # Get the index of the maximum value
ran_vector[max_index] = -1  # Replace it with -1 giving it indexing.

print("Random Vector:", ran_vector)
    

 The random vector is :
 [0.69436003 0.53133104 0.23498197 0.44689058 0.69152692 0.3790842
 0.35034633 0.47791685 0.44480057 0.66091257 0.7756736  0.01325127
 0.88933997 0.90440513 0.48029724]
Random Vector: [ 0.69436003  0.53133104  0.23498197  0.44689058  0.69152692  0.3790842
  0.35034633  0.47791685  0.44480057  0.66091257  0.7756736   0.01325127
  0.88933997 -1.          0.48029724]
