In [1]:
                      # Practical 4.1
# Mean: The average value of the elements along the specified axis.

# Standard Deviation: A measure of how spread out the numbers are in the array. It indicates the amount of variation or dispersion.

# Variance: The square of the standard deviation, which provides a measure of how much the values in the array differ from the mean. 

import numpy as np

# Generate a random 2D array (4 rows and 5 columns)
arr_2d = np.random.rand(4, 5)

# Compute the mean, standard deviation, and variance along the second axis (axis=1)

# Axis 0: Refers to the vertical axis (downwards along rows). When performing operations along this axis, you compute statistics for each column.

# Axis 1: Refers to the horizontal axis (across columns). When performing operations along this axis, you compute statistics for each row.

mean_values = np.mean(arr_2d, axis=1)
std_deviation = np.std(arr_2d, axis=1)
variance_values = np.var(arr_2d, axis=1)

# Display the results
print("2D Array:")
print(arr_2d)
print("\nMean along the second axis:")
print(mean_values)
print("\nStandard Deviation along the second axis:")
print(std_deviation)
print("\nVariance along the second axis:")
print(variance_values)


2D Array:
[[0.20064204 0.56337608 0.01305539 0.60807553 0.69155868]
 [0.92359507 0.51972971 0.85854534 0.54424111 0.92399991]
 [0.62531695 0.70946933 0.51316039 0.88742421 0.39753721]
 [0.10315848 0.19149696 0.4139991  0.39152936 0.78010462]]

Mean along the second axis:
[0.41534154 0.75402223 0.62658162 0.3760577 ]

Standard Deviation along the second axis:
[0.2620254  0.1830156  0.16747331 0.23386726]

Variance along the second axis:
[0.06865731 0.03349471 0.02804731 0.0546939 ]


In [3]:
                          # Practical 4.2
    
# Write a NumPy program to compute the covariance matrix of two given arrays.
    
# Importing the NumPy library
import numpy as np

# Creating two arrays
x = np.array([0, 1, 5])
y = np.array([3, 1, 0])

# Displaying the original arrays
print("Original array x:", x)
print("Original array y:", y)

# Calculating the covariance matrix of arrays x and y
cov_matrix = np.cov(x, y)

# Displaying the covariance matrix
print("Covariance matrix of x and y:\n", cov_matrix)    

Original array x: [0 1 5]
Original array y: [3 1 0]
Covariance matrix of x and y:
 [[ 7.         -3.5       ]
 [-3.5         2.33333333]]


In [8]:
                      # Practical 4.3
    
# Write a Python program to count number of occurrences of each value in a given array of non-negative integers.

# Function to count occurrences using a dictionary
def count_occurrences(arr):
    # Initialize an empty dictionary to store counts
    counts = {}
    
    # Iterate through each number in the array
    for num in arr:
        if num in counts:
            counts[num] += 1  # Increment count if number is already in dictionary
        else:
            counts[num] = 1   # Initialize count to 1 if number is not in dictionary
            
    return counts

# Example array of non-negative integers
array = [8, 1, 2, 2, 3, 0, 4, -3,-3]

# Count occurrences and print the result
occurr = count_occurrences(array)
print("Occurrences using dictionary:", occurr)

Occurrences using dictionary: {8: 1, 1: 1, 2: 2, 3: 1, 0: 1, 4: 1, -3: 2}


In [11]:
                  # Practical 4.4
# Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.
 
import numpy as np

ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]

x = np.percentile(ages, 80)  # it is use for calculating the percentile score.

print(" The 80th percentile for all element is :\n",x)    

 The 80th percentile for all element is :
 48.0
